// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';

// Publishing to GitHub Pages as a project site:
//   https://<user>.github.io/<repo>/
// Update `site` and `base` with the real repository slug before first deploy.
const REPO_OWNER = 'avvale';
const REPO_NAME = 'aurora-catalyst-docs';

// `base` stays the same in dev and prod so hardcoded links in frontmatter
// (hero actions, etc.) work identically in both environments. The
// locale-aware root redirect lives in `src/pages/index.astro`.
export default defineConfig({
  site: `https://${REPO_OWNER}.github.io`,
  base: `/${REPO_NAME}`,
  // The satellite how-to was absorbed into the getting-started tutorial.
  // Keep the old URLs alive — docs URLs are contracts. The source key is
  // base-relative (Astro emits the redirect file at the dist root, served under
  // `base`), but the destination is used verbatim in the meta refresh — so it
  // must include the `base` prefix or it resolves to the wrong site root.
  redirects: {
    '/en/guides/auth/connect-a-satellite-to-an-aurora-hub':
      `/${REPO_NAME}/en/tutorials/getting-started/install-satellite/`,
    '/es/guides/auth/connect-a-satellite-to-an-aurora-hub':
      `/${REPO_NAME}/es/tutorials/getting-started/install-satellite/`,
  },
  integrations: [
    // Renders ```mermaid fenced code blocks as diagrams. MUST be listed before
    // starlight() so its rehype plugin runs in the right order. `autoTheme`
    // syncs the diagram palette with Starlight's light/dark `data-theme`.
    mermaid({
      theme: 'neutral',
      autoTheme: true,
      enableLog: false,
    }),
    starlight({
      title: 'Aurora Catalyst',
      description:
        'Documentation for the Aurora Catalyst ecosystem — CLI, framework, and conventions.',
      // Project styles layered on top of Starlight's theme.
      customCss: ['./src/styles/custom.css'],
      // `eta` is the CLI codegen template language and is not in Shiki's bundle.
      // Alias it to the bundled ERB grammar (same `<% %>` delimiters) so the
      // auto-generated API reference snippets highlight instead of falling back
      // to txt with a build warning. (Those pages are produced by `pnpm sync`.)
      expressiveCode: {
        shiki: {
          langAlias: { eta: 'erb' },
        },
      },
      defaultLocale: 'en',
      locales: {
        en: { label: 'English', lang: 'en' },
        es: { label: 'Español', lang: 'es' },
      },
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: `https://github.com/${REPO_OWNER}/${REPO_NAME}`,
        },
      ],
      // Sidebar follows the Diátaxis framework:
      //   tutorials → learn by doing
      //   guides    → solve a concrete task
      //   reference → consult technical facts
      //   concepts  → understand the why
      // Starlight v0.39+ removed autogenerated groups with a `label`. A localized
      // group is now a manual group: `{ label, items: [{ autogenerate: { directory } }] }`.
      sidebar: [
        {
          label: 'Tutorials',
          translations: { es: 'Tutoriales' },
          // Manual groups so the group label can be translated per-locale. The CLI
          // install and project-scaffold pages sit ABOVE the "Aurora Hub" group as
          // prerequisite links instead of inside it — each page sets `sidebar.hidden`
          // to drop out of the autogenerated group.
          items: [
            { slug: 'tutorials' },
            {
              slug: 'tutorials/getting-started/install-cli',
              label: 'Install Aurora Catalyst CLI',
              translations: { es: 'Instalar CLI Aurora Catalyst' },
            },
            {
              slug: 'tutorials/getting-started/install-aurora',
              label: 'Install Aurora Catalyst',
              translations: { es: 'Instalar Aurora Catalyst' },
            },
            {
              label: 'Aurora Hub',
              translations: { es: 'Aurora Hub' },
              items: [{ autogenerate: { directory: 'tutorials/getting-started' } }],
            },
            {
              label: 'Frontend',
              translations: { es: 'Frontend' },
              items: [{ autogenerate: { directory: 'tutorials/frontend' } }],
            },
          ],
        },
        {
          label: 'How-to guides',
          translations: { es: 'Guías' },
          // Manual subgroups so the directory-derived labels render capitalized
          // ("Backend"/"Frontend"/"Workflow") instead of the raw lowercase dir
          // names a flat `autogenerate: { directory: 'guides' }` would produce.
          items: [
            { slug: 'guides' },
            {
              label: 'Backend',
              translations: { es: 'Backend' },
              items: [{ autogenerate: { directory: 'guides/backend' } }],
            },
            {
              label: 'Frontend',
              translations: { es: 'Frontend' },
              items: [{ autogenerate: { directory: 'guides/frontend' } }],
            },
            {
              label: 'Workflow',
              translations: { es: 'Workflow' },
              items: [{ autogenerate: { directory: 'guides/workflow' } }],
            },
          ],
        },
        {
          label: 'Reference',
          translations: { es: 'Referencia' },
          items: [
            { slug: 'reference' },
            {
              label: 'Frontend',
              translations: { es: 'Frontend' },
              items: [{ autogenerate: { directory: 'reference/frontend' } }],
            },
            {
              label: 'CLI Commands',
              translations: { es: 'Comandos CLI' },
              items: [{ autogenerate: { directory: 'reference/cli-commands' } }],
            },
            {
              label: 'API',
              collapsed: true,
              items: [{ autogenerate: { directory: 'reference/api' } }],
            },
          ],
        },
        {
          label: 'Concepts',
          translations: { es: 'Conceptos' },
          // Manual subgroups so the directory-derived labels render capitalized
          // ("Backend"/"Frontend"/"Workflow") instead of the raw lowercase dir
          // names a flat `autogenerate: { directory: 'concepts' }` would produce.
          // The Concepts overview sits at the top, above the subgroups.
          items: [
            { slug: 'concepts' },
            {
              label: 'Backend',
              translations: { es: 'Backend' },
              items: [{ autogenerate: { directory: 'concepts/backend' } }],
            },
            {
              label: 'Frontend',
              translations: { es: 'Frontend' },
              items: [{ autogenerate: { directory: 'concepts/frontend' } }],
            },
            {
              label: 'Workflow',
              translations: { es: 'Workflow' },
              items: [{ autogenerate: { directory: 'concepts/workflow' } }],
            },
          ],
        },
        {
          label: 'Change history',
          translations: { es: 'Historial de cambios' },
          collapsed: true,
          items: [{ autogenerate: { directory: 'changes' } }],
        },
      ],
      editLink: {
        baseUrl: `https://github.com/${REPO_OWNER}/${REPO_NAME}/edit/main/`,
      },
      lastUpdated: true,
    }),
  ],
});
